name: flutter_record
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  record: ^3.0.0+3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  audio_service: ^0.18.15
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.39
  audio_session: ^0.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
